name: playground
version: 1.1.1

dependencies:
  react: ^5.0.0
  w_common: ^1.20.0
  over_react: ^3.5.0
  built_value: ">=6.8.2 <7.0.0"
  built_collection: ">=3.0.5 <5.0.0"

dev_dependencies:
  args: ">=1.5.0 <2.0.0"
  build_runner: ^1.7.1
  build_test: ^0.10.9
  build_web_compilers: ^2.6.1
  built_value_generator: ">=4.6.1 <7.0.0"
  dart_dev: ^3.2.1
  dart_style: ^1.3.1
  dependency_validator: ^1.4.0